version: '3'

volumes:
  node_modules:
  postgres:

services:
  app:
    image: node:20
    ports:
      - 5010:5000
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    tty: true
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5442:5432
